//! Same vault, same queries as `paper_hand` — but the `Note` impl is
//! generated by `#[derive(Note)]` instead of being hand-written. If
//! both examples produce identical output, the macro is faithful.
//!
//! Run with:
//! ```bash
//! cargo run -p vaultdb-orm --example paper_derive
//! ```

use std::fs;

use serde::{Deserialize, Serialize};
use tempfile::TempDir;
use vaultdb_orm::{Expr, Note, Query, SortKey, Vault};

#[derive(Debug, Clone, Serialize, Deserialize, Note)]
#[note(folder = "3-Notes", filter = "tags contains type/paper")]
struct Paper {
    #[serde(rename = "_name")]
    title: String,
    year: i32,
    tags: Vec<String>,
    #[serde(default)]
    rating: Option<String>,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let vault_dir = build_demo_vault()?;
    let vault = Vault::with_root(vault_dir.path().to_path_buf());

    println!("--- all papers ---");
    let papers: Vec<Paper> = Query::<Paper>::new(&vault).fetch()?;
    for p in &papers {
        println!("  {} ({}) {:?}", p.title, p.year, p.tags);
    }

    println!("\n--- papers from >= 2023, sorted by year desc ---");
    let recent: Vec<Paper> = Query::<Paper>::new(&vault)
        .filter(Expr::parse("year >= 2023")?)
        .order_by(SortKey {
            field: "year".into(),
            descending: true,
        })
        .fetch()?;
    for p in &recent {
        println!("  {} ({})", p.title, p.year);
    }

    println!("\n--- first unrated paper ---");
    let first: Option<Paper> = Query::<Paper>::new(&vault)
        .filter(Expr::parse("rating missing")?)
        .first()?;
    if let Some(p) = first {
        println!("  {} ({})", p.title, p.year);
    } else {
        println!("  (none)");
    }

    println!("\n--- count of all papers ---");
    let n = Query::<Paper>::new(&vault).count()?;
    println!("  {n}");

    // Sanity: the derive must have produced both the const and the filter.
    assert_eq!(<Paper as Note>::FOLDER, "3-Notes");
    assert!(<Paper as Note>::discriminator().is_some());

    Ok(())
}

fn build_demo_vault() -> std::io::Result<TempDir> {
    let dir = TempDir::new()?;
    let folder = dir.path().join("3-Notes");
    fs::create_dir_all(&folder)?;

    let entries = [
        (
            "Attention Is All You Need",
            "---\ntags: [type/paper, topic/attention]\nyear: 2017\nrating: deep\n---\nTransformer paper.\n",
        ),
        (
            "BERT",
            "---\ntags: [type/paper, topic/nlp]\nyear: 2018\n---\nBidirectional encoder.\n",
        ),
        (
            "GPT-4 Technical Report",
            "---\ntags: [type/paper, topic/llm]\nyear: 2023\nrating: read\n---\nReport.\n",
        ),
        (
            "Transformer Architecture",
            "---\ntags: [type/concept]\nyear: 2017\n---\nConcept note.\n",
        ),
    ];

    for (name, content) in entries {
        fs::write(folder.join(format!("{name}.md")), content)?;
    }

    Ok(dir)
}
