[workspace]
resolver = "2"
members = [
    "crates/vaultdb-core",
    "crates/vaultdb",
    "crates/vaultdb-mcp",
]

[workspace.package]
version = "0.4.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/rusenbb/vaultdb"
readme = "README.md"

[profile.release]
lto = true
codegen-units = 1
strip = true
