//! [`FieldRef`]: a typed handle to a frontmatter field.
//!
//! Generated by `#[derive(Note)]` as one zero-cost accessor per struct
//! field. Each accessor returns a `FieldRef` bound to the matching
//! frontmatter key — possibly overridden by `#[serde(rename = "...")]`
//! — and the `FieldRef`'s methods build typed [`Expr`] predicates:
//!
//! ```ignore
//! Paper::year().gte(2024) & Paper::tags().contains("topic/ai")
//! ```
//!
//! The DSL is intentionally one layer thin over the core AST: each
//! method returns a `vaultdb_core::Expr`, so user code can mix typed
//! accessors with `Expr::parse(...)` or hand-built AST nodes freely.

use vaultdb_core::{CompareOp, Expr, Predicate, Value};

/// A typed handle to a frontmatter field.
///
/// Construct via the accessor methods emitted by `#[derive(Note)]`
/// (e.g. `Paper::year()`) or directly with [`FieldRef::new`] for
/// fields not modelled by a struct.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FieldRef {
    name: &'static str,
}

impl FieldRef {
    /// Wrap a static field name.
    pub const fn new(name: &'static str) -> Self {
        Self { name }
    }

    /// The field name as it appears in frontmatter (after any
    /// `#[serde(rename)]` resolution by the derive macro).
    pub const fn name(&self) -> &'static str {
        self.name
    }

    fn field_string(&self) -> String {
        self.name.to_string()
    }

    /// `field = value`.
    pub fn eq(&self, v: impl Into<Value>) -> Expr {
        Expr::Predicate(Predicate::Equals {
            field: self.field_string(),
            value: v.into(),
        })
    }

    /// `field != value`.
    pub fn ne(&self, v: impl Into<Value>) -> Expr {
        Expr::Predicate(Predicate::Compare {
            field: self.field_string(),
            op: CompareOp::Ne,
            value: v.into(),
        })
    }

    /// `field < value`.
    pub fn lt(&self, v: impl Into<Value>) -> Expr {
        Expr::Predicate(Predicate::Compare {
            field: self.field_string(),
            op: CompareOp::Lt,
            value: v.into(),
        })
    }

    /// `field <= value`.
    pub fn le(&self, v: impl Into<Value>) -> Expr {
        Expr::Predicate(Predicate::Compare {
            field: self.field_string(),
            op: CompareOp::Le,
            value: v.into(),
        })
    }

    /// `field > value`.
    pub fn gt(&self, v: impl Into<Value>) -> Expr {
        Expr::Predicate(Predicate::Compare {
            field: self.field_string(),
            op: CompareOp::Gt,
            value: v.into(),
        })
    }

    /// `field >= value`.
    pub fn ge(&self, v: impl Into<Value>) -> Expr {
        Expr::Predicate(Predicate::Compare {
            field: self.field_string(),
            op: CompareOp::Ge,
            value: v.into(),
        })
    }

    /// `field contains value` — list-membership for `Vec<…>` fields,
    /// substring for strings.
    pub fn contains(&self, v: impl Into<Value>) -> Expr {
        Expr::Predicate(Predicate::Contains {
            field: self.field_string(),
            value: v.into(),
        })
    }

    /// `field matches /regex/`.
    pub fn matches(&self, regex: impl Into<String>) -> Expr {
        Expr::Predicate(Predicate::Matches {
            field: self.field_string(),
            regex: regex.into(),
        })
    }

    /// `field startswith prefix`.
    pub fn starts_with(&self, v: impl Into<String>) -> Expr {
        Expr::Predicate(Predicate::StartsWith {
            field: self.field_string(),
            value: v.into(),
        })
    }

    /// `field endswith suffix`.
    pub fn ends_with(&self, v: impl Into<String>) -> Expr {
        Expr::Predicate(Predicate::EndsWith {
            field: self.field_string(),
            value: v.into(),
        })
    }

    /// `field exists` — present and non-null.
    pub fn exists(&self) -> Expr {
        Expr::Predicate(Predicate::Exists {
            field: self.field_string(),
        })
    }

    /// `field missing` — absent or null. Equivalent to `IS NULL`.
    pub fn is_null(&self) -> Expr {
        Expr::Predicate(Predicate::Missing {
            field: self.field_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn eq_builds_expected_predicate() {
        let f = FieldRef::new("year");
        let e = f.eq(2024);
        assert_eq!(
            e,
            Expr::Predicate(Predicate::Equals {
                field: "year".into(),
                value: Value::Integer(2024),
            })
        );
    }

    #[test]
    fn contains_accepts_strings() {
        let f = FieldRef::new("tags");
        let e = f.contains("topic/ai");
        assert_eq!(
            e,
            Expr::Predicate(Predicate::Contains {
                field: "tags".into(),
                value: Value::String("topic/ai".into()),
            })
        );
    }

    #[test]
    fn bitand_combines_field_predicates() {
        let combined = FieldRef::new("year").ge(2024) & FieldRef::new("tags").contains("topic/ai");
        match combined {
            Expr::And(parts) => assert_eq!(parts.len(), 2),
            other => panic!("expected And, got {:?}", other),
        }
    }
}
