//! [`RelationRef`]: a typed handle to a wiki-link relation.
//!
//! Generated by `#[derive(Note)]` for any struct field tagged
//! `#[note(wikilink)]` (or `#[note(backlink)]` for incoming).
//! Methods build the graph-flavoured `Expr` variants — `LinksTo` and
//! `LinkedFrom` — that the query AST already supports:
//!
//! ```ignore
//! // "Papers that link to anything tagged topic/attention" — a join
//! // via the citation graph in one query.
//! Paper::query(&vault).filter(
//!     Paper::cites().any(Paper::tags().contains("topic/attention"))
//! ).fetch()?;
//! ```
//!
//! In Phase 5 the relation does NOT auto-materialise the linked
//! records — the struct field (typically `Vec<String>`) is populated
//! only from frontmatter, so a `#[note(wikilink)]`-tagged field
//! typically lives alongside `#[serde(default)]` and stays empty.
//! Eager relation resolution lands in a later release.

use vaultdb_core::{Expr, LinkPredicate};

/// Direction of a relation: outgoing (`[[link]]` pointing out from the
/// note) versus incoming (other notes linking *to* this one).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RelationDir {
    Outgoing,
    Incoming,
}

/// A typed handle to a wiki-link relation.
#[derive(Debug, Clone, Copy)]
pub struct RelationRef {
    dir: RelationDir,
}

impl RelationRef {
    /// Outgoing relation: this note's `[[wikilinks]]`.
    pub const fn outgoing() -> Self {
        Self {
            dir: RelationDir::Outgoing,
        }
    }

    /// Incoming relation: notes that wiki-link to this one.
    pub const fn incoming() -> Self {
        Self {
            dir: RelationDir::Incoming,
        }
    }

    /// Direction of the relation (for callers that need to introspect).
    pub const fn direction(&self) -> RelationDir {
        self.dir
    }

    /// "Links to a note named `target`."
    ///
    /// `Paper::cites().to("Attention Is All You Need")`
    pub fn to(&self, target: impl Into<String>) -> Expr {
        let lp = LinkPredicate::Target(target.into());
        match self.dir {
            RelationDir::Outgoing => Expr::LinksTo(lp),
            RelationDir::Incoming => Expr::LinkedFrom(lp),
        }
    }

    /// "Links to any record matching `predicate`."
    ///
    /// `Paper::cites().any(Paper::tags().contains("topic/attention"))`
    pub fn any(&self, predicate: Expr) -> Expr {
        let lp = LinkPredicate::Where(Box::new(predicate));
        match self.dir {
            RelationDir::Outgoing => Expr::LinksTo(lp),
            RelationDir::Incoming => Expr::LinkedFrom(lp),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use vaultdb_core::{Expr, Predicate, Value};

    #[test]
    fn outgoing_to_target() {
        let r = RelationRef::outgoing();
        let e = r.to("BERT");
        match e {
            Expr::LinksTo(LinkPredicate::Target(name)) => assert_eq!(name, "BERT"),
            other => panic!("expected LinksTo target, got {:?}", other),
        }
    }

    #[test]
    fn outgoing_any_wraps_sub_expression() {
        let r = RelationRef::outgoing();
        let inner = Expr::Predicate(Predicate::Equals {
            field: "tags".into(),
            value: Value::String("topic/attention".into()),
        });
        let e = r.any(inner.clone());
        match e {
            Expr::LinksTo(LinkPredicate::Where(boxed)) => assert_eq!(*boxed, inner),
            other => panic!("expected LinksTo Where, got {:?}", other),
        }
    }

    #[test]
    fn incoming_uses_linked_from_variant() {
        let r = RelationRef::incoming();
        let e = r.to("BERT");
        assert!(matches!(e, Expr::LinkedFrom(LinkPredicate::Target(_))));
    }
}
